modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/abused/Industrial-Meat/issues/"
license="MIT"

[[mods]]
modId="industrialmeat"
version="1.0.4"
displayName="Industrial Meat"
displayURL="https://github.com/abused/Industrial-Meat/"
credits="Minefactory Reloaded for the idea."
authors="abused_master"
description='''
The meat is back!
'''

[[dependencies.industrialmeat]]
    modId = "industrialforegoing"
    mandatory = true
    versionRange = "[3.2,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.industrialmeat]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.0.1,)"
    ordering = "NONE"
    side = "BOTH"